### ISSUE TITLE
Adding more localization

### ISSUE THREAD

**Issue by rosdyana** [novalagung/muslimboardindo#24]
Dear @novalagung 

Do you have a plan to add more localization?
My Taiwanese Muslim asked me if MuslimBoard can support their languages (Traditional Chinese zh-tw).

**Comment by novalagung** [comment]
hi @rosdyana, I'd love to have more localization added to the project.
however, I can't speak traditional Chinese.

do you think it's something that you or your friend can help with? really appreciate it if that's possible.
maybe a text or spreadsheet containing the mapping between english vs traditional should be good, and then I can proceed with the coding changes.

PR is also fine, the localization code is centralized on https://github.com/novalagung/muslimboard/blob/master/extension/assets/internal/scripts/i18n.js
