### ISSUE TITLE
Crowdin for muslimboard (web) localization

### ISSUE THREAD

**Issue by novalagung** [novalagung/muslimboardindo#29]

**Comment by ilhamsyahids** [comment]
Do you open or plan to use [Crowdin](https://crowdin.com/)?

**Comment by novalagung** [comment]
the localization was already added to Muslim board extension and website as per [v2.5.2 release](https://github.com/novalagung/muslimboard/releases/tag/v2.5.2) and [v2.5.5](https://github.com/novalagung/muslimboard/releases/tag/v2.5.5) respectively.

I'll do some research first on how to use Crowdin, just wanted to make sure it fits this project or not.

Thanks for the idea btw!

**Comment by novalagung** [comment]
closing this ticket we will use the manual translation route
