### ISSUE TITLE
Correction of a hadith 

### ISSUE THREAD

**Issue by Poligum** [novalagung/muslimboardindo#49]
Assalamu alaikum wa rahmatullahi wa barakatuh,
There is a messing letter in the quote 
 مَا نَقَصَتْ صَدَقَةٌ مِنْ مَالٍ وَمَا زَادَ اللَّهُ عَبْدًا بِعَفْوٍ إِلاَّ عِزًّا وَمَا تَوَاضَعَ أَحَدٌ لِلَّهِ إِلاَّ رَفَعَهُ اللَّ

Charity does not decrease wealth, no one forgives another except that Allah increases his honor, and no one humbles himself for the sake of Allah except that Allah raises his status

at the end of the hadith in arabic a letter is messing:

  مَا نَقَصَتْ صَدَقَةٌ مِنْ مَالٍ وَمَا زَادَ اللَّهُ عَبْدًا بِعَفْوٍ إِلاَّ عِزًّا وَمَا تَوَاضَعَ أَحَدٌ لِلَّهِ إِلاَّ رَفَعَهُ **_اللَّ_** ❌

 مَا نَقَصَتْ صَدَقَةٌ مِنْ مَالٍ وَمَا زَادَ اللَّهُ عَبْدًا بِعَفْوٍ إِلاَّ عِزًّا وَمَا تَوَاضَعَ أَحَدٌ لِلَّهِ إِلاَّ رَفَعَهُ **_اللَّهُ✅_**
source of the hadith :https://sunnah.com/muslim:2588

**Comment by novalagung** [comment]
@Poligum wa'alaikumsalam warohmatullah wabarakatuh.

thank you, I really appreciate the issue report. I'll work to fix it this weekend asap
