### ISSUE TITLE
Link show incorrect page

### ISSUE THREAD

**Issue by FerdinaKusumah** [novalagung/muslimboardindo#78]
It showing link under quotes that is clickable
![Screenshot from 2024-01-29 17-15-47](https://github.com/novalagung/muslimboard/assets/19812460/fcd6e4ee-8ed6-4243-b351-4ab10bc878cd)

But it's showing incorrect link when user clicked
![Screenshot from 2024-01-29 17-18-28](https://github.com/novalagung/muslimboard/assets/19812460/ebb69272-117f-4ba8-b001-5ebfd8510ded)

**Comment by novalagung** [comment]
whoaa, this is messed up. I guess the domain is already invalid. I'm fixing it right away

**Comment by novalagung** [comment]
@FerdinaKusumah thanks a lot for reporting this! I really appreciate it
