### ISSUE TITLE
Error Fetching Data

### ISSUE THREAD

**Issue by arsyadbruh** [novalagung/muslimboardindo#80]
recently i have problem
![image](https://github.com/novalagung/muslimboard/assets/71438511/f066ef61-77e1-4c5d-9d1d-764298f4a8d0)

My internet is smooth and there are no problems, i open a console and got an error like this
![image](https://github.com/novalagung/muslimboard/assets/71438511/bb505777-62dc-4ae1-be74-827a31a040ff)

is the Muslim board service down? or there is a bug or error on my computer?

**Comment by FerdinaKusumah** [comment]
Samething happens here

![Screenshot from 2024-03-01 10-08-29](https://github.com/novalagung/muslimboard/assets/19812460/8e7d6efb-7485-4883-8dc2-d57067611dd7)

Trying to hit the api and got this
![image](https://github.com/novalagung/muslimboard/assets/19812460/2ea82530-0542-473a-b9a8-655dc7133825)

**Comment by alfanzain** [comment]
Confirmed. It was happened since about 2 days ago.

**Comment by alfanzain** [comment]
It has fixed since today. Maybe external issue?

![image](https://github.com/novalagung/muslimboard/assets/4216529/5a6b0371-3b37-4a2c-8f60-9aa2bb8210a1)
