### ISSUE TITLE
OpenStreetMap Reverse Geolocation API is deprecated

### ISSUE THREAD

**Issue by novalagung** [novalagung/muslimboardindo#85]
The reverse geolocation API is deprecated https://nominatim.org/release-docs/latest/api/Reverse/
Need to replace it with AddressLookup instead https://nominatim.org/release-docs/latest/api/Lookup/

**Comment by FerdinaKusumah** [comment]
Hi @novalagung just read the documentation about lookup api, it needs to pass `osm_ids` as param.
Not sure if it can pass `lat` and `long`.

After searching i got another solution that is using `search` api first. then get the `osm_ids` to get the detail information using lookup api


Example may like this:

1. Call this [search api](https://nominatim.openstreetmap.org/search?format=json&q=52.399550700000006,13.048066846939687) and get the `osm_ids`
2. Call this [lookup api](https://nominatim.openstreetmap.org/lookup?osm_ids=w50637691&format=json) to get the equal response `reverse` api by using `lookup api` 

What do you think for this solutions ?


[Revision]
I'm sorry After reading carefully we only need to add more param to get response slightly same as `reverse` api
with param `addressdetails`
take a look this [api](https://nominatim.openstreetmap.org/search?format=json&q=52.399550700000006,13.048066846939687&addressdetails=1)

**Comment by novalagung** [comment]
thanks @FerdinaKusumah
