### ISSUE TITLE
Error retrieving prayer time data

### ISSUE THREAD

**Issue by Ahmad-Alaya** [novalagung/muslimboardindo#89]
Whenever a new browser tab is opened, a message appears stating that there is an error retrieving prayer times. It is really annoying

![image](https://github.com/novalagung/muslimboard/assets/39459495/0d2b7d55-b736-47ab-81a0-d63c0606d955)

**Comment by novalagung** [comment]
we are currently working on this issue. we will release another version once it is fixed

**Comment by novalagung** [comment]
@Ahmad-Alaya I updated the backend with changes to fix this issue. I will close it if there is no new update on this issue until next week.

Thanks!
